/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAddPackage {
    }
    interface AppHome {
    }
    interface AppMap {
    }
    interface AppPackageDetail {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppAddPackageElement extends Components.AppAddPackage, HTMLStencilElement {
    }
    var HTMLAppAddPackageElement: {
        prototype: HTMLAppAddPackageElement;
        new (): HTMLAppAddPackageElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppMapElement extends Components.AppMap, HTMLStencilElement {
    }
    var HTMLAppMapElement: {
        prototype: HTMLAppMapElement;
        new (): HTMLAppMapElement;
    };
    interface HTMLAppPackageDetailElement extends Components.AppPackageDetail, HTMLStencilElement {
    }
    var HTMLAppPackageDetailElement: {
        prototype: HTMLAppPackageDetailElement;
        new (): HTMLAppPackageDetailElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-add-package": HTMLAppAddPackageElement;
        "app-home": HTMLAppHomeElement;
        "app-map": HTMLAppMapElement;
        "app-package-detail": HTMLAppPackageDetailElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppAddPackage {
    }
    interface AppHome {
    }
    interface AppMap {
    }
    interface AppPackageDetail {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-add-package": AppAddPackage;
        "app-home": AppHome;
        "app-map": AppMap;
        "app-package-detail": AppPackageDetail;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-add-package": LocalJSX.AppAddPackage & JSXBase.HTMLAttributes<HTMLAppAddPackageElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-map": LocalJSX.AppMap & JSXBase.HTMLAttributes<HTMLAppMapElement>;
            "app-package-detail": LocalJSX.AppPackageDetail & JSXBase.HTMLAttributes<HTMLAppPackageDetailElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
