/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppAddPackage {
    }
    interface AppAgenda {
    }
    interface AppCalendar {
    }
    interface AppFilter {
    }
    interface AppHome {
    }
    interface AppMap {
    }
    interface AppPackageDetail {
    }
    interface AppRoot {
    }
}
declare global {
    interface HTMLAppAddPackageElement extends Components.AppAddPackage, HTMLStencilElement {
    }
    var HTMLAppAddPackageElement: {
        prototype: HTMLAppAddPackageElement;
        new (): HTMLAppAddPackageElement;
    };
    interface HTMLAppAgendaElement extends Components.AppAgenda, HTMLStencilElement {
    }
    var HTMLAppAgendaElement: {
        prototype: HTMLAppAgendaElement;
        new (): HTMLAppAgendaElement;
    };
    interface HTMLAppCalendarElement extends Components.AppCalendar, HTMLStencilElement {
    }
    var HTMLAppCalendarElement: {
        prototype: HTMLAppCalendarElement;
        new (): HTMLAppCalendarElement;
    };
    interface HTMLAppFilterElement extends Components.AppFilter, HTMLStencilElement {
    }
    var HTMLAppFilterElement: {
        prototype: HTMLAppFilterElement;
        new (): HTMLAppFilterElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppMapElement extends Components.AppMap, HTMLStencilElement {
    }
    var HTMLAppMapElement: {
        prototype: HTMLAppMapElement;
        new (): HTMLAppMapElement;
    };
    interface HTMLAppPackageDetailElement extends Components.AppPackageDetail, HTMLStencilElement {
    }
    var HTMLAppPackageDetailElement: {
        prototype: HTMLAppPackageDetailElement;
        new (): HTMLAppPackageDetailElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-add-package": HTMLAppAddPackageElement;
        "app-agenda": HTMLAppAgendaElement;
        "app-calendar": HTMLAppCalendarElement;
        "app-filter": HTMLAppFilterElement;
        "app-home": HTMLAppHomeElement;
        "app-map": HTMLAppMapElement;
        "app-package-detail": HTMLAppPackageDetailElement;
        "app-root": HTMLAppRootElement;
    }
}
declare namespace LocalJSX {
    interface AppAddPackage {
    }
    interface AppAgenda {
    }
    interface AppCalendar {
    }
    interface AppFilter {
    }
    interface AppHome {
    }
    interface AppMap {
    }
    interface AppPackageDetail {
    }
    interface AppRoot {
    }
    interface IntrinsicElements {
        "app-add-package": AppAddPackage;
        "app-agenda": AppAgenda;
        "app-calendar": AppCalendar;
        "app-filter": AppFilter;
        "app-home": AppHome;
        "app-map": AppMap;
        "app-package-detail": AppPackageDetail;
        "app-root": AppRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-add-package": LocalJSX.AppAddPackage & JSXBase.HTMLAttributes<HTMLAppAddPackageElement>;
            "app-agenda": LocalJSX.AppAgenda & JSXBase.HTMLAttributes<HTMLAppAgendaElement>;
            "app-calendar": LocalJSX.AppCalendar & JSXBase.HTMLAttributes<HTMLAppCalendarElement>;
            "app-filter": LocalJSX.AppFilter & JSXBase.HTMLAttributes<HTMLAppFilterElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-map": LocalJSX.AppMap & JSXBase.HTMLAttributes<HTMLAppMapElement>;
            "app-package-detail": LocalJSX.AppPackageDetail & JSXBase.HTMLAttributes<HTMLAppPackageDetailElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
        }
    }
}
